### PR TITLE
Add Libresoft IT Solutions

### PR DESCRIPTION
**Pull request by Avasz**
Thanks :)

### CODE REVIEW

**Comment by mesaugat** [comment]
Thank you. Can you please remove the full stop from the description.

**Comment by ashokbhattarai** [comment]
Professional Computer System P. Ltd, www.pcs.com.np

**Comment by mesaugat** [comment]
Hello @ashokbhattarai. Do you know how to make a pull request or should I make one for you?

You can click on this link https://github.com/mesaugat/tech-companies-in-nepal/blob/master/README.md and press the edit button to add your company.

Thanks

**Comment by ashokbhattarai** [comment]
I am new to github and I didn't get how to open PR, so I made a comment and
new file was created. Please let me know if something is wrong.

**Comment by mesaugat** [comment]
Thanks @Avasz

**Comment by mesaugat** [comment]
No problem @ashokbhattarai I'll add your company to the list.

**Comment by mesaugat** [comment]
@Avasz Is your company located at Dillibazaar? I see Maharajgunj on your website.

**Pull request merged**
